---
name: Bot-BasicBot-Pluggable-Module-RSS
version: 0.02
author:
  - 'Mario Domgoergen <dom@math.uni-bonn.de>'
abstract: RSS feed aggregator for your bot
license: perl
resources:
  license: ~
requires:
  Bot::BasicBot::Pluggable: 0
  Digest::MD5: 0
  File::Spec: 0
  POE: 0
  POE::Component::RSSAggregator: 0
  String::Format: 0
build_requires:
  Test::More: 0
provides:
  Bot::BasicBot::Pluggable::Module::RSS:
    file: lib/Bot/BasicBot/Pluggable/Module/RSS.pm
    version: 0.02
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
